\documentclass{article}
\usepackage{underscore}
\usepackage[utf8]{inputenc}
\usepackage{longtable}
\usepackage[margin=1in]{geometry}
\usepackage[spanish]{babel}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage[table,xcdraw]{xcolor}
\usepackage{fancyvrb}
\usepackage{lscape}
\usepackage{anysize}
\usepackage{fancyhdr}%encabezados y pies de página
\usepackage{color}

\lfoot[a1] {\tiny\textcolor{violet}{VHIR-UEB-FOR-013v.01}}

\lhead{\includegraphics[width=.28\textwidth]{./images/UEBblanc.jpg}}
\rhead{\leftmark}

\pagestyle{fancy}


\marginsize{3.0cm}{3.5cm}{2.5cm}{2.5cm}
\renewcommand{\baselinestretch}{1.3} % per canviar interlineado
\renewcommand*\footnoterule{}

% \backgroundsetup{
%   position={current page.south west},
%   vshift=-22pt,
%   hshift=98pt,
%   angle= 90,
%   contents = VHIR-UEB-FOR-013v.01,
%   scale= 0.7,
%   color= violet
%   }

\hypersetup{
  colorlinks=true,
  linkcolor=violet
}

\begin{document}

\title{\begin{figure}[htbp]
       \centering
       \includegraphics[width=60mm]{images/UEBblanc.jpg}
       \includegraphics[width=35mm]{images/IR.jpg}
       \end{figure}
       \vspace{1cm}
       Continuación estudio B2326:\\
       Realización de Heatmaps y diagramas de Venn\\
       \footnotetext{\footnoterule{\tiny\textcolor{violet}{VHIR-UEB-FOR-013v.01}}}\\
       {\normalsize Cristina Sole - B4040 }\\
       }


\author{Ricardo Gonzalo, Ferran Brians\'{o} y Alex S\'{a}nchez \\ 
        Unitat d'Estad\'{i}stica i Bioinform\`{a}tica \\
        Vall d'Hebron Institut de Recerca (VHIR) \\
        }
        
\maketitle
\newpage

\tableofcontents

\newpage
%--------------------------------------------------------------------------------------------------------------------------------------------
\section{Introducción}
%-------------------------------------------------------------------------------------------
En octubre del 2016 se realizó un estudio de análisis de expresión diferencial de miRNAs utilizando la tecnología de qPCR (2016-B2326), con placas de la casa comercial Exiqon. En dicho estudio se realizaron una serie de comparaciones donde se obtuvieron una serie de listas de miRNAs diferencialmente expresados. En el presente estudio los investigadores están interesados en ver los genes comunes que existen entre varias de aquellas comparaciones (utilizando los Diagramas de Venn) y ver si existen clusters de expresión, mediante la representación de los heatmaps.

%-----------------------
\subsection{Objetivos}
%-----------------------
Las comparaciones en que están interesados los investigadores en observar si hay genes comunes son las siguientes:

\begin{enumerate}
  \item (Brote Remisión vs Brote No Remisión) vs (PostBrote NoRemisión vs Brote NoRemisión)
  \item (Brote Remisión vs Brote No Remisión) vs (PostBrote Remisión vs Brote Remisión) 
  \item (Brote Remisión vs Brote No Remisión) vs (PostBrote Remisión vs PostBrote No Remisión)
  \item (PostBrote NoRemisión vs Brote NoRemisión) vs (PostBrote Remisión vs Brote Remisión)
\end{enumerate}

Se realizarán heatmaps de todas las comparaciones individuales que se hicieron en el estudio anterior:

\begin{itemize}
  \item Brote No Remisión vs PostBrote No Remisión 
  \item Brote Remisión vs PostBrote Remisión 
  \item Brote Remisión vs Brote No Remisión
  \item PostBrote Remisión vs PostBrote No Remisión
\end{itemize}

%-----------------------
\subsection{Los datos para el análisis}
%-----------------------
En el caso de la búsqueda de los genes comunes, los datos para el análisis son las listas de genes diferencialmente expresados ("TopTables") que se generaron en el estudio anterior, una para cada comparación.

A continuación se muestran las cinco primeras filas de cada uno de las listas utilizadas en el presente estudio (cuadro \ref{tab1}, cuadro \ref{tab2}, cuadro \ref{tab3}, cuadro \ref{tab4}):
<<packages,echo=FALSE,message=FALSE>>=
require(knitr)
#require(stargazer)
require(compareGroups)
library(xtable)
require(devtools)
#install_github("miriammota/mmotaF",force=TRUE)
library(VennDiagram)
library(gridExtra) #para poder añadir el título al gráfico
library(gplots)
library(RColorBrewer)
@


<<echo=FALSE, results="hide",message=FALSE>>=
# include this code chunk as-is to set options
opts_chunk$set(comment=NA,prompt = TRUE, tidy = FALSE, fig.width = 5, fig.height = 5,echo = FALSE, message = FALSE, warning = FALSE)
Sys.setlocale("LC_TIME", "C")
@


<<dir,echo=FALSE>>=
workingDir <- getwd()
dataDir <- file.path(workingDir, "dades")
resultsDir <- file.path(workingDir, "results")
setwd(workingDir)
@

<<carregadades,echo=FALSE,results="hide">>=
#llegim les diferents toptables
top1<-read.table(file.path(dataDir,"topTab_comp1_POSTBROT.NOvsBROT.NO.csv"),header = TRUE,sep="\t")
top2<-read.table(file.path(dataDir,"topTab_comp2_POSTBROT.SIvsBROT.SI.csv"),header = TRUE,sep="\t")
top3<-read.table(file.path(dataDir,"topTab_comp3_BROT.SIvsBROT.NO.csv"),header = TRUE,sep="\t")
top4<-read.table(file.path(dataDir,"topTab_comp4_POSTBROT.SIvsPOSTBROT.NO.csv"),header = TRUE,sep="\t")
@


<<mostrararhcivo,results='asis'>>=
print(xtable(head(top1),caption="Primeras cinco filas de la comparación POSTBROT.NOvsBROT.NO", tabular.environment = 'longtable', floating = FALSE,size="tiny",label="tab1"))

print(xtable(head(top2),caption="Primeras cinco filas de la comparación POSTBROT.SIvsBROT.SI", tabular.environment = 'longtable', floating = FALSE,size="tiny",label="tab2"))

print(xtable(head(top3),caption="Primeras cinco filas de la comparación BROT.SIvsBROT.NO", tabular.environment = 'longtable', floating = FALSE,size="tiny",label="tab3"))

print(xtable(head(top4),caption="Primeras cinco filas de la comparación POSTBROT.SIvsPOSTBROT.NO", tabular.environment = 'longtable', floating = FALSE,size="tiny",label="tab4"))
@
\\

En el caso de los heatmaps, los datos para el análisis, son los datos de valores de Ct normalizados del estudio anterior. Se preparan dos archivos de datos normalizados, uno dónde no está la muestra NL022, y otro donde además tampoco está la muestra NL021, descartadas en el estudio anterior por motivos de calidad.

<<loaddata2>>=
normData1<-read.csv2(file.path(dataDir,"normdata.dCts.csv"),header = TRUE,sep=";")
normData2<-read.csv2(file.path(dataDir,"normdata.dCts.wo.csv"),header = TRUE,sep=";")
@

\newpage
\newpage
%-------------------------------------------------------------------------------------------------------------------------------------------
\section{Análisis y Resultados}
%-------------------------------------------------------------------------------------------------------------------------------------------
En esta sección se realizarán los diagramas de Venn de las comparaciones en que está interesada la investigadora y posteriormente los Heatmaps. Para los \texttt{diagramas de Venn}, se proporcionará una figura donde se verán gráficamente los miRNAs comunes y no comunes entre las diferentes comparaciones, y un archivo con extensión .csv que se puede abrir con Excel, para cada diagrama de Venn dónde se podrán identificar los miRNAs en cada caso. En el archivo habrá dos columnas, con ceros y unos, una para cada comparación. Para saber los miRNA comunes en las comparaciones analizadas, se han de buscar que en las celdas del excel, aparezca un ``1'' en las dos columnas.\\
En el caso de los \texttt{Heatmaps}, se proporcionará una figura del mismo para cada comparación, donde el color azul representará menor expresión del miRNA, mientras que el color rojo, representará mayor expresión. Por temas estéticos los valores de Ct normalizados que se han utilizado para hacer los Heatmaps se han centrado (se ha calculado la media y desviación estandar de todos los valores, y a cada uno de ellos se les ha restado la media y se ha dividido por la desviación estándar).

\subsection{Diagramas de Venn}
\subsubsection{Comparación (Brote Remisión vs Brote No Remisión) vs (PostBrote NoRemisión vs Brote NoRemisión)}
Como se puede observar en la siguiente figura (\ref{fig:venn1}), el número de miRNA comunes con un pvalor inferior a 0.05 es de 1, concretamente el miRNA \texttt{hsa-miR-10a-5p}.
<<VDfunction,echo=FALSE,results='hide'>>=
vennfrom2csv<-function(file1,name1,file2,name2,pval) {
  ##seleccionem els cutoffs
  pass1 <- file1[which(file1$pVal<pval),]
  #dim(pass1)
  pass2 <- file2[which(file2$pVal<pval),]
  #dim(pass2)
  list1 <- as.character(pass1$gene)
  #length(list1)
  list2 <- as.character(pass2$gene)
  #length(list2)

  list <- c(list1, list2)
  #length(list)
  list <- sort(unique(list))
  #length(list)

  ####es crea un data.frame que omplim de 0 i després de 1 si hi coexisteixen en les dues llistes
  df <- data.frame(genes = list, l1 = rep(0,length(list)), l2 = rep(0,length(list)))
  #head(df)

  df$l1 <- as.numeric((df$genes %in% list1)==T)
  df$l2 <- as.numeric((df$genes %in% list2)==T)

  ##Fem el diagrama de venn
  overlap<-calculate.overlap(x=list("list1"=list1,"list2"=list2))

  draw.pairwise.venn(length(overlap$a1),length(overlap$a2),length(overlap$a3),
                  category=c(name1,name2),scaled = TRUE,euler.d = TRUE, 
                 fill = c("blue", "red"),lty = "blank",cat.pos = c(190, 190))
  
  ##es grava l'arxiu de text on s'indica quin gen hi és a cada venn
  colnames(df)<-c("miRNA",name1,name2)
  write.csv(df, file=file.path(resultsDir,paste("mult.comp.",name1,"_",name2,".csv",sep="")))
}
@


<<venn1, echo=FALSE,results='hide',message=FALSE>>=
#Brote Remisión vs Brote No Remisión) vs (PostBrote NoRemisión vs Brote NoRemisión)
file1 <- top3
name1 <-"Brote.SI vs Brote.No"
file2<- top1
name2<-"PostBrote.No vs Brote.No"

pdf(file.path(resultsDir,"VennDiagram1.pdf"))
grid.arrange(gTree(children=vennfrom2csv(file1,name1,file2,name2,0.05)),top=paste("Venn Diagram for: ",name1, " vs ",name2," (pval<0.05)",sep=""))
dev.off()  
@
\begin{figure}
\centering
\includegraphics[scale=0.4]{/home/rgonzalo/Documents/Estudis/2017-01-CristinaSole-VHIR-qPCR-B4040/results/VennDiagram1.pdf}
\caption{\label{fig:venn1}Diagrama de Venn para las comparaciones Brote.SI vs Brote.No vs PostBrote.No vs Brote.No con pvalor$<$0.05}
\end{figure}

\subsubsection{Comparación (Brote Remisión vs Brote No Remisión) vs (PostBrote Remisión vs Brote Remisión)}
Como se puede observar en la siguiente figura (\ref{fig:venn2}), no existe ningún miRNA común entre estas dos comparaciones.
<<venn2, echo=FALSE,results='hide',message=FALSE>>=
file1 <- top3
name1 <-"Brote.SI vs Brote.No"
file2 <- top2
name2<-"PostBrote.Si vs Brote.Si"

pdf(file.path(resultsDir,"VennDiagram2.pdf"))
grid.arrange(gTree(children=vennfrom2csv(file1,name1,file2,name2,0.05)),top=paste("Venn Diagram for: ",name1, " vs ",name2," (pval<0.05)",sep=""))
dev.off()  
@
\begin{figure}
\centering
\includegraphics[scale=0.4]{/home/rgonzalo/Documents/Estudis/2017-01-CristinaSole-VHIR-qPCR-B4040/results/VennDiagram2.pdf}
\caption{\label{fig:venn2}Diagrama de Venn para las comparaciones Brote.SI vs Brote.No vs PostBrote.Si vs Brote.Si con pvalor$<$0.05}
\end{figure}

\subsubsection{Comparación (Brote Remisión vs Brote No Remisión) vs (PostBrote Remisión vs PostBrote No Remisión)}
Como se puede observar en la siguiente figura (\ref{fig:venn3}), no existe ningún miRNA común entre estas dos comparaciones.
<<venn3, echo=FALSE,results='hide',message=FALSE>>=
file1 <- top3
name1 <-"Brote.SI vs Brote.No"
file2 <- top4
name2<-"PostBrote.Si vs PostBrote.No"

pdf(file.path(resultsDir,"VennDiagram3.pdf"))
grid.arrange(gTree(children=vennfrom2csv(file1,name1,file2,name2,0.05)),top=paste("Venn Diagram for: ",name1, " vs ",name2," (pval<0.05)",sep=""))
dev.off()  
@
\begin{figure}
\centering
\includegraphics[scale=0.4]{/home/rgonzalo/Documents/Estudis/2017-01-CristinaSole-VHIR-qPCR-B4040/results/VennDiagram3.pdf}
\caption{\label{fig:venn3}Diagrama de Venn para las comparaciones Brote.SI vs Brote.No vs PostBrote.Si vs PostBrote.No con pvalor$<$0.05}
\end{figure}

\subsubsection{Comparación (PostBrote No Remisión vs Brote No Remisión) vs (PostBrote Remisión vs Brote Remisión)}
Como se puede observar en la siguiente figura (\ref{fig:venn4}), solamente hay un miRNA común entre estas dos comparaciones (\texttt{hsa-miR-195-5p})
<<venn4, echo=FALSE,message=FALSE,results='hide'>>=
file1 <- top1
name1 <-"PostBrote.No vs Brote.No"
file2 <- top2
name2<-"PostBrote.Si vs Brote.Si"

pdf(file.path(resultsDir,"VennDiagram4.pdf"))
grid.arrange(gTree(children=vennfrom2csv(file1,name1,file2,name2,0.05)),top=paste("Venn Diagram for: ",name1, " vs ",name2," (pval<0.05)",sep=""))
dev.off()  
@
 \begin{figure}
 \centering
 \includegraphics[scale=0.4]{/home/rgonzalo/Documents/Estudis/2017-01-CristinaSole-VHIR-qPCR-B4040/results/VennDiagram4.pdf}
 \caption{\label{fig:venn4}Diagrama de Venn para las comparaciones PostBrote.No vs Brote.No vs PostBrote.Si vs Brote.Si con pvalor$<$0.05}
 \end{figure}

%------------------------------------------------------------------------------------------
\newpage
\subsection{Heatmaps}
\subsubsection{Comparación Brote No Remisión vs PostBrote No Remisión}
<<preparadadesheatmap1,fig.align='center',fig.height=5,fig.width=5>>=
#ens quedem amb les columnes que interesen i les ordenem
hm1Data<-normData2[,1:13]
hm1Data<-hm1Data[,c(1,2,4,6,8,10,12,3,5,7,9,11,13)]
#guardem els noms dels gens
rnames <- hm1Data[,1]
#Ho transforment en una matrix
mat.hm1Data<-data.matrix(hm1Data[,-1])

rownames(mat.hm1Data) <- rnames
my_palette <- colorRampPalette(c("red", "white", "blue"))(n = 299)
par(cex.main=0.7)

heatmap.2(mat.hm1Data,
  main = "Brote No Remisión vs PostBrote No Remisión",
  key = FALSE,
  scale="column",
  na.rm = TRUE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  notecol="black",      # change font color of cell labels to black
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",6 ),rep("lightgreen",6)))  
@

<<hm2pdf1,message=FALSE,results='hide'>>=
pdf(file.path(resultsDir,"Heatmap1.pdf"))
par(cex.main=0.7)
heatmap.2(mat.hm1Data,
  main = "Brote No Remisión vs PostBrote No Remisión",
  key = FALSE,
  scale="column",
  na.rm = TRUE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  notecol="black",      # change font color of cell labels to black
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",6 ),rep("lightgreen",6)))
dev.off()
@


\subsubsection{Comparación Brote Remisión vs PostBrote Remisión}
<<preparadadesheatmap2,fig.align='center',fig.height=5,fig.width=5>>=
#ens quedem amb les columnes que interesen i les ordenem
hm2Data<-normData2[,c(1,14:27)]
hm2Data<-hm2Data[,c(1,2,4,6,8,10,12,14,3,5,7,9,11,13,15)]
#guardem els noms dels gens
rnames <- hm2Data[,1]
#Ho transforment en una matrix
mat.hm2Data<-data.matrix(hm2Data[,-1])
rownames(mat.hm2Data) <- rnames
par(cex.main=0.7)

heatmap.2(mat.hm2Data,
  main = "Brote Remisión vs PostBrote Remisión", 
  key = FALSE,
  scale="column",
  na.rm = TRUE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  notecol="black", 
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",7 ),rep("lightgreen",7)))   
@

<<hm2pdf2,message=FALSE,results='hide'>>=
pdf(file.path(resultsDir,"Heatmap2.pdf"))
par(cex.main=0.7)
heatmap.2(mat.hm2Data,
  main = "Brote Remisión vs PostBrote Remisión", 
  scale="column",
  na.rm = TRUE,
  key = FALSE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  notecol="black", 
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",7 ),rep("lightgreen",7)))
dev.off()
@


\subsubsection{Comparación Brote Remisión vs Brote No Remisión}
<<preparadadesheatmap3,fig.align='center',fig.height=5,fig.width=5>>=
#ens quedem amb les columnes que interesen 
hm3Data<-normData1[,c(1,2,4,5,7,9,11,13,15,17,19,21,23,25,27)]
#guardem els noms dels gens
rnames <- hm3Data[,1]
#Ho transforment en una matrix
mat.hm3Data<-data.matrix(hm3Data[,-1])

rownames(mat.hm3Data) <- rnames
par(cex.main=0.7)

heatmap.2(mat.hm3Data,
  main = "Brote Remisión vs Brote No Remisión", 
  notecol="black", 
  scale="column",
  na.rm = TRUE,
  key = FALSE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",7 ),rep("lightgreen",7)))   
@

<<hm2pdf3,message=FALSE,results='hide'>>=
pdf(file.path(resultsDir,"Heatmap3.pdf"))
par(cex.main=0.7)
heatmap.2(mat.hm3Data,
  main = "Brote Remisión vs Brote No Remisión", 
  notecol="black", 
  scale="column",
  na.rm = TRUE,
  key = FALSE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",7 ),rep("lightgreen",7)))
dev.off()
@

\subsubsection{Comparación PostBrote Remisión vs PostBrote No Remisión}
<<preparadadesheatmap4,fig.align='center',fig.height=5,fig.width=5>>=
#ens quedem amb les columnes que interesen 
hm4Data<-normData1[,c(1,3,6,8,10,12,14,16,18,20,22,24,26,28)]
#guardem els noms dels gens
rnames <- hm4Data[,1]
#Ho transforment en una matrix i ho scalem perque el heatmap surti més bonic
mat.hm4Data<-data.matrix(hm4Data[,-1])

rownames(mat.hm4Data) <- rnames
par(cex.main=0.7)

heatmap.2(mat.hm4Data,
  main = "PostBrote Remisión vs PostBrote No Remisión", 
  notecol="black", 
  key = FALSE,
  scale="column",
  na.rm = TRUE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",6 ),rep("lightgreen",7)))   
@

<<hm2pdf4,message=FALSE,results='hide'>>=
pdf(file.path(resultsDir,"Heatmap4.pdf"))
par(cex.main=0.7)
heatmap.2(mat.hm4Data,
  main = "PostBrote Remisión vs PostBrote No Remisión", 
  notecol="black", 
  key = FALSE,
  scale="column",
  na.rm = TRUE,
  cexRow = 0.4 ,
  cexCol = 0.5 ,
  trace="none",         # turns off trace lines inside the heat map
  margins =c(12,9),     # widens margins around plot
  col=my_palette,       # use on color palette defined earlier
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA",
  ColSideColors = c(rep("darkgreen",6 ),rep("lightgreen",7)))
dev.off()
@


%-------------------------------------------------------------------------------------------------------------------------------------------
\section{Conclusiones}
%----------------------------------------------------------------------------
En el presente estudio se han realizado varios Diagramas de Venn para valorar el número de genes comunes que existían entre diferentes listas de miRNA diferencialmente expresados, procedentes de un análisis anterior (ver estudio 2016-CristinaSole-VHIR-B2326). Sólamente se ha encontrado un miRNA en común en dos de las comparaciones propuestas:
\begin{itemize}
  \item (Brote Remisión vs Brote No Remisión) vs (PostBrote No-
Remisión vs Brote NoRemisión): \textbf{miRNA \texttt{hsa-miR-10a-5p}}
  \item (PostBrote No Remisión vs Brote No Remisión) vs (Post-
Brote Remisión vs Brote Remisión): \textbf{miRNA \texttt{hsa-miR-195-5p}}
\end{itemize}
\\
También se han realizado varios heatmaps de las comparaciones incluídas en el estudio anterior. En lineas generales no se observan grupos de miRNAs con expresión característica y diferencial entre las condiciones analizadas.
%-----------------------------------------------------------------------------------------------------------------

\section{Otras consideraciones}

En el momento de analizar los resultados obtenidos, se ha de tener en cuenta que en el estudio anterior del cual provienen los datos,  no se corrigió el pvalor resultante por el número de test realizado, lo que pudiera provocar la aparición de algún falso positivo.\\

Todos los análisis han sido realizados con el programa estadístico ``R''( \textttt{\Sexpr{R.Version()$versi}, Copyright (C) 2015 The R Foundation for Statistical Computing} ).\\

\newline
\textbf{Para poder evaluar la utilidad del resultado de nuestro trabajo os rogamos que nos informéis de los productos científicos como consecuencia de los mismos (comunicaciones, artículos, tesis, etc.) Así mismo nos gustaría que incluyerais el siguiente párrafo en el apartado de agradecicimentos de tus manuscritos.}\\

\textbf{El análisis estadístico ha sido llevado a cabo en la Unidad de Estadística y Bioinformática (UEB) del Instituto de Investigación del Hospital de Vall Hebrón (VHIR).}

\end{document}
