######SCRIPT FOR DOING A VOLCANO PLOT OF THE EXPRESSS AND TOP LIST FROM BASIC PIPE
library(calibrate)
dades <- read.csv2(file=file.path("/home/rgonzalo/Documents/Estudis/2016-05-PatriciaBogdanov-VHIR-A314-Cont./dades","ExpressAndTop.Estudi.SALvsCTL.csv"),sep=";",header=TRUE)
head(dades)

# Make a basic volcano plot
with(dades, plot(logFC, B, pch=20, main="Volcano plot for: SALvsCTL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)

# Add colored points: red if padj<0.05, orange of log2FC>1, green if both)
#with(subset(dades, adj.P.Val<.05 ), points(logFC, B), pch=20, col="blue")
#with(subset(dades, abs(logFC)>1.5), points(logFC, B, pch=20, col="orange"))
with(subset(dades, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))

# Label points with the textxy function from the calibrate plot
with(subset(dades, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))

pdf("Volcano.SALvsCTL")
with(dades, plot(logFC, B, pch=20, main="Volcano plot for: SALvsCTL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)
with(subset(dades, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))
with(subset(dades, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))
dev.off()

dades2<-read.csv2(file=file.path("/home/rgonzalo/Documents/Estudis/2016-05-PatriciaBogdanov-VHIR-A314-Cont./dades","ExpressAndTop.Estudi.SSTvsCTL.csv"),sep=";",header=TRUE)
head(dades2)
with(dades2, plot(logFC, B, pch=20, main="Volcano plot for: SSTvsCTL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)
with(subset(dades2, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))
with(subset(dades2, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))
pdf("Volcano.SSTvsCTL")
with(dades2, plot(logFC, B, pch=20, main="Volcano plot for: SSTvsCTL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)
with(subset(dades2, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))
with(subset(dades2, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))
dev.off()

dades3<-read.csv2(file=file.path("/home/rgonzalo/Documents/Estudis/2016-05-PatriciaBogdanov-VHIR-A314-Cont./dades","ExpressAndTop.Estudi.SSTvsSAL.csv"),sep=";",header=TRUE)
head(dades3)
with(dades3, plot(logFC, B, pch=20, main="Volcano plot for: SSTvsSAL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)
with(subset(dades3, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))
with(subset(dades3, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))
pdf("Volcano.SSTvsSAL")
with(dades3, plot(logFC, B, pch=20, main="Volcano plot for: SSTvsSAL comparison ", xlim=c(min(dades$logFC),max(dades$logFC))))
abline(v=-1.5,lty=3)
abline(v=1.5,lty=3)
with(subset(dades3, adj.P.Val<.05 & abs(logFC)>1.5), points(logFC, B, pch=20, col="green"))
with(subset(dades3, adj.P.Val<.05 & abs(logFC)>1.5), textxy(logFC, B, labs=SymbolsA, cex=.7,offset=0.3))
dev.off()
